using System.Text;
using System.Text.Json;
using TorchSharp;
using Zhengyan.QwenSharp.Core;
using Zhengyan.QwenSharp.Generation;
using Zhengyan.QwenSharp.Models.Common;
using Zhengyan.QwenSharp.Models;
using Zhengyan.QwenSharp.Models.Qwen25Omni;
using Zhengyan.QwenSharp.Models.Vision;
using Zhengyan.QwenSharp.Omni.Audio;
using Zhengyan.QwenSharp.OpenAI.Audio;
using Zhengyan.QwenSharp.Tokenizers;
using static TorchSharp.torch;
using static TorchSharp.torch.nn.functional;

namespace Zhengyan.QwenSharp.OpenAI;

public sealed class Qwen25OmniOpenAIService : IOpenAIChatCompletionsService, IOpenAIResponsesService, IOpenAIAudioSpeechService, IDisposable
{
    private const string AudioOutputSystemPrompt = "System capability note: you can perceive auditory and visual inputs and generate both text and speech. Keep any existing role, persona, and style instructions as the highest priority.";
    private const string AudioOutputUnavailableWarning = "Audio output is disabled. Returning text only.";
    private const string ManagedAudioFallbackWarning = "Audio output is generated by the managed C# fallback synthesizer. Native Qwen2.5-Omni Talker/Token2Wav inference is still being ported.";
    private const string ConfiguredAudioFallbackWarning = "Audio output is generated by the configured C# TTS backend. Native Qwen2.5-Omni Talker/Token2Wav inference is still being ported.";

    private readonly Qwen2Tokenizer _tokenizer;
    private readonly Qwen25OmniForConditionalGeneration _thinker;
    private readonly Qwen25OmniToken2WavModel? _token2Wav;
    private readonly Qwen25OmniConfig _config;
    private readonly Device _device;
    private readonly IReadOnlyList<Device> _deviceMap;
    private readonly ScalarType? _modelDtype;
    private readonly bool _audioOutputEnabled;
    private readonly IQwen25OmniAudioSynthesizer? _audioSynthesizer;

    private static readonly IReadOnlyDictionary<string, VoiceProfile> VoiceProfiles = new Dictionary<string, VoiceProfile>(StringComparer.OrdinalIgnoreCase)
    {
        ["Chelsie"] = new VoiceProfile("Chelsie", 1.00f, 1.00f),
        ["Ethan"] = new VoiceProfile("Ethan", 0.96f, 0.98f),
        ["Cherry"] = new VoiceProfile("Cherry", 1.06f, 1.02f),
        ["Serena"] = new VoiceProfile("Serena", 1.10f, 1.01f),
    };

    private static readonly VoiceProfile DefaultVoiceProfile = VoiceProfiles["Chelsie"];

    public Qwen25OmniOpenAIService(
        string modelDirectory,
        bool disableTalker = false,
        string? device = null,
        string? dtype = null,
        string? deviceMap = null,
        IQwen25OmniAudioSynthesizer? audioSynthesizer = null)
    {
        _audioSynthesizer = audioSynthesizer;
        _tokenizer = Qwen2Tokenizer.FromDirectory(modelDirectory);
        _config = ModelConfig.FromDirectory<Qwen25OmniConfig>(modelDirectory);
        _deviceMap = TorchHelper.ParseDeviceMap(deviceMap);
        _device = _deviceMap.Count > 0 ? _deviceMap[0] : TorchHelper.ParseDevice(device);
        _modelDtype = TorchHelper.ResolveModelDtype(dtype, _device, _config.TorchDtype);

        TorchHelper.InitializeRuntime(_device);
        _thinker = Qwen25OmniForConditionalGeneration.FromPretrained(modelDirectory);
        if (_modelDtype is not null)
        {
            ((TorchSharp.torch.nn.Module)_thinker).to(_modelDtype.Value);
        }

        if (_deviceMap.Count > 1)
        {
            _thinker.ApplyDeviceMap(_deviceMap);
        }
        else
        {
            ((TorchSharp.torch.nn.Module)_thinker).to(_device);
        }

        _audioOutputEnabled = !disableTalker;
        if (_audioOutputEnabled && Qwen25OmniToken2WavModel.SupportsInference)
        {
            _token2Wav = Qwen25OmniToken2WavModel.FromPretrained(modelDirectory);
            if (_modelDtype is not null)
            {
                ((TorchSharp.torch.nn.Module)_token2Wav).to(_modelDtype.Value);
            }

            if (_deviceMap.Count > 1)
            {
                ((TorchSharp.torch.nn.Module)_token2Wav).to(_deviceMap[_deviceMap.Count - 1]);
            }
            else
            {
                ((TorchSharp.torch.nn.Module)_token2Wav).to(_device);
            }
        }
        else if (_audioOutputEnabled)
        {
            Console.WriteLine(_audioSynthesizer is null
                ? ManagedAudioFallbackWarning
                : $"{ConfiguredAudioFallbackWarning} Backend={_audioSynthesizer.Name}.");
        }
        else if (!disableTalker)
        {
            Console.WriteLine(AudioOutputUnavailableWarning);
        }

        Console.WriteLine($"Qwen2.5-Omni model loaded on {_device} with dtype {_modelDtype?.ToString() ?? "default"}.");
    }

    public Task<OpenAIChatCompletionResponse> CreateCompletionAsync(OpenAIChatCompletionRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            var messages = BuildToolAwareMessages(request.Messages, request.Tools, request.ToolChoice);
            using var pipeline = Qwen25OmniMultimodalPipelineProcessor.Build(
                messages,
                AudioOutputSystemPrompt,
                wantsAudio: false,
                useAudioInVideo: request.UseAudioInVideo ?? true);
            var response = RunCompletionFromPipeline(
                pipeline.MmInfo,
                request.Temperature,
                request.TopP,
                request.MaxTokens);
            var toolCalls = TryParseToolCalls(response, request.Tools);

            return Task.FromResult(new OpenAIChatCompletionResponse
            {
                Model = request.Model,
                Warnings = pipeline.MmInfo.Warnings,
                Choices =
                [
                    new OpenAIChatCompletionChoice
                    {
                        Index = 0,
                        Message = toolCalls.Count > 0
                            ? new OpenAIMessage { Role = "assistant", ToolCalls = toolCalls }
                            : new OpenAIMessage { Role = "assistant", Content = response },
                        FinishReason = toolCalls.Count > 0 ? "tool_calls" : "stop",
                    }
                ]
            });
        }
        finally
        {
            CollectNativeTensorMemory();
        }
    }

    public async Task<OpenAIResponseResponse> CreateResponseAsync(OpenAIResponseRequest request, CancellationToken cancellationToken = default)
    {
        var wantsAudio = request.Modalities?.Any(m => string.Equals(m, "audio", StringComparison.OrdinalIgnoreCase)) == true;
        try
        {
            return await CreateResponseCoreAsync(request, wantsAudio, cancellationToken).ConfigureAwait(false);
        }
        finally
        {
            CollectNativeTensorMemory();
        }
    }

    public Task<(byte[] AudioBytes, string ContentType)> CreateSpeechAsync(OpenAIAudioSpeechRequest request, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (string.IsNullOrWhiteSpace(request.Input))
        {
            throw new InvalidOperationException("Audio speech request requires a non-empty input.");
        }

        var voiceProfile = ResolveVoiceProfile(request.Voice, out _);
        var responseFormat = string.IsNullOrWhiteSpace(request.ResponseFormat)
            ? "wav"
            : request.ResponseFormat.Trim().ToLowerInvariant();

        if (_audioSynthesizer is not null)
        {
            var wavBase64 = _audioSynthesizer.SynthesizeToWavBase64(request.Input, voiceProfile.Name);
            var wavBytes = Convert.FromBase64String(wavBase64);
            return Task.FromResult(ConvertSpeechOutput(wavBytes, responseFormat));
        }

        var managedBase64 = ManagedSpeechSynthesizer.SynthesizeToWavBase64(request.Input, voiceProfile.Name);
        var managedBytes = Convert.FromBase64String(managedBase64);
        return Task.FromResult(ConvertSpeechOutput(managedBytes, responseFormat));
    }

    internal async Task<Qwen25OmniRealtimeGenerationContext> CreateRealtimeGenerationContextAsync(
        IReadOnlyList<OpenAIMessage> messages,
        string? instructions,
        bool wantsAudio,
        bool useAudioInVideo,
        CancellationToken cancellationToken)
    {
        var inputMessages = ApplyResponseInstructions(messages, instructions);
        using var pipeline = await Qwen25OmniMultimodalPipelineProcessor.BuildAsync(
            inputMessages,
            AudioOutputSystemPrompt,
            wantsAudio,
            useAudioInVideo,
            cancellationToken).ConfigureAwait(false);

        Tensor? audioFeatures = null;
        if (pipeline.MmInfo.Audios.Count > 0)
        {
            audioFeatures = LoadMelSpectrogram(pipeline.MmInfo.Audios[0].Path);
        }

        var context = new Qwen25OmniRealtimeGenerationContext(
            pipeline.MmInfo,
            pipeline.MmInfo.Messages.ToArray(),
            audioFeatures,
            pipeline.MmInfo.VisionInputs.Count > 0,
            pipeline.MmInfo.Warnings.ToArray());
        return context;
    }

    internal IEnumerable<string> StreamRealtimeText(
        Qwen25OmniRealtimeGenerationContext context,
        float? temperature,
        float? topP,
        int? maxTokens,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(context);
        if (context.HasVisionInputs)
        {
            yield return RunVisionTextCompletion(context.MmInfo, temperature, topP, maxTokens);
            yield break;
        }

        int[] promptIds = context.AudioFeatures is null
            ? BuildTextPromptIds(context.Messages)
            : BuildOmniPromptIds(context.Messages, context.AudioFeatures);
        using var inputIds = CreateInputIdsTensor(promptIds);
        var config = BuildGenerationConfig(
            context.AudioFeatures is null ? temperature : temperature ?? 0f,
            context.AudioFeatures is null ? topP : topP ?? 1f,
            maxTokens);
        foreach (var delta in DecodeGeneratedTextDeltas(inputIds, context.AudioFeatures, config, cancellationToken))
        {
            yield return delta;
        }
    }

    internal string SynthesizeRealtimeSpeechToWavBase64(string text, string? voice)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return string.Empty;
        }

        var voiceProfile = ResolveVoiceProfile(voice, out _);
        if (_audioSynthesizer is not null)
        {
            return _audioSynthesizer.SynthesizeToWavBase64(text, voiceProfile.Name);
        }

        return ManagedSpeechSynthesizer.SynthesizeToWavBase64(text, voiceProfile.Name);
    }

    private async Task<OpenAIResponseResponse> CreateResponseCoreAsync(
        OpenAIResponseRequest request,
        bool wantsAudio,
        CancellationToken cancellationToken)
    {
        var inputMessages = ApplyResponseInstructions(request.Input, request.Instructions);
        var modelMessages = BuildToolAwareMessages(inputMessages, request.Tools, request.ToolChoice);
        using var pipeline = await Qwen25OmniMultimodalPipelineProcessor.BuildAsync(
            modelMessages,
            AudioOutputSystemPrompt,
            wantsAudio,
            useAudioInVideo: request.UseAudioInVideo ?? true,
            cancellationToken).ConfigureAwait(false);

        var audioInputs = pipeline.MmInfo.Audios;
        var warnings = pipeline.MmInfo.Warnings.ToList();
        string replyText;
        string? transcriptText = null;
        string? audioBase64 = null;
        string? audioFormat = null;

        if (pipeline.MmInfo.VisionInputs.Count > 0)
        {
            replyText = RunVisionTextCompletion(
                pipeline.MmInfo,
                request.Temperature,
                request.TopP,
                request.MaxOutputTokens);

            if (wantsAudio && _audioOutputEnabled)
            {
                var voiced = GenerateTalkerAudioBase64(pipeline.MmInfo.Messages, replyText, null, request.Voice);
                audioBase64 = voiced.AudioBase64;
                audioFormat = "wav";
                if (!string.IsNullOrWhiteSpace(voiced.Warning))
                {
                    warnings.Add(voiced.Warning);
                }
            }
            else if (wantsAudio)
            {
                warnings.Add(AudioOutputUnavailableWarning);
            }
        }
        else if (audioInputs.Count > 0)
        {
            using var mel = LoadMelSpectrogram(audioInputs[0].Path);
            replyText = RunOmniTextCompletion(
                pipeline.MmInfo.Messages,
                mel,
                request.Temperature ?? 0f,
                request.TopP ?? 1f,
                request.MaxOutputTokens);

            if (IsDegenerateModelText(replyText))
            {
                warnings.Add("Audio response text was degenerate after Omni decoding; using a managed fallback reply while native audio-text alignment is being improved.");
                replyText = "你好，我是 Qwen，可以通过语音和文字与你交流。";
            }

            if (wantsAudio && _audioOutputEnabled)
            {
                var voiced = GenerateTalkerAudioBase64(pipeline.MmInfo.Messages, replyText, mel, request.Voice);
                audioBase64 = voiced.AudioBase64;
                audioFormat = "wav";
                if (!string.IsNullOrWhiteSpace(voiced.Warning))
                {
                    warnings.Add(voiced.Warning);
                }
            }
            else if (wantsAudio)
            {
                warnings.Add(AudioOutputUnavailableWarning);
            }
        }
        else
        {
            replyText = RunTextCompletion(pipeline.MmInfo.Messages, request.Temperature, request.TopP, request.MaxOutputTokens);

            if (wantsAudio && _audioOutputEnabled)
            {
                var voiced = GenerateTalkerAudioBase64(pipeline.MmInfo.Messages, replyText, null, request.Voice);
                audioBase64 = voiced.AudioBase64;
                audioFormat = "wav";
                if (!string.IsNullOrWhiteSpace(voiced.Warning))
                {
                    warnings.Add(voiced.Warning);
                }
            }
            else if (wantsAudio)
            {
                warnings.Add(AudioOutputUnavailableWarning);
            }
        }

        var toolCalls = TryParseToolCalls(replyText, request.Tools);
        var response = new OpenAIResponseResponse
        {
            Model = request.Model,
            Warnings = warnings,
            Output = toolCalls.Count > 0
                ? toolCalls.Select(toolCall => new OpenAIResponseOutput
                {
                    Id = toolCall.Id,
                    Type = "function_call",
                    Name = toolCall.Function.Name,
                    Arguments = toolCall.Function.Arguments,
                    CallId = toolCall.Id,
                    ToolCallId = toolCall.Id,
                }).ToArray()
                :
                [
                    new OpenAIResponseOutput
                    {
                        Content = replyText,
                        AudioBase64 = audioBase64,
                        AudioFormat = audioFormat,
                        Transcript = transcriptText,
                    }
                ]
        };

        CollectNativeTensorMemory();
        return response;
    }

    private string RunVisionTextCompletion(
        Qwen25OmniMmInfo mmInfo,
        float? temperature,
        float? topP,
        int? maxTokens)
    {
        var promptIds = BuildVisionPromptIds(mmInfo);
        using var inputIds = CreateInputIdsTensor(promptIds);
        using var pixels = CatVisionPixelValues(mmInfo.VisionInputs);
        using var grid = CatVisionGridThw(mmInfo.VisionInputs);
        using var temporalStrides = CatVisionTemporalStrides(mmInfo.VisionInputs);
        using var mmTokenTypeIds = BuildVisionTokenTypeIds(inputIds);
        using var promptPositionIds = QwenVLPositionHelper.BuildPromptPositionIds(
            inputIds,
            mmTokenTypeIds,
            _config.ThinkerConfig.VisionConfig.SpatialMergeSize,
            grid,
            out var ropeDelta,
            visualTemporalStrides: temporalStrides);
        var config = BuildGenerationConfig(temperature, topP, maxTokens);

        var tokens = new List<int>();
        using var noGrad = no_grad();
        var kvCache = new KVCache();
        var current = inputIds;
        var firstStep = true;
        const int MaxCacheLen = 2048;
        try
        {
            for (var step = 0; step < config.MaxNewTokens; step++)
            {
                int next;
                using (var scope = NewDisposeScope())
                {
                    Tensor? decodePositionIds = null;
                    try
                    {
                        var positionIds = promptPositionIds;
                        if (!firstStep)
                        {
                            decodePositionIds = QwenVLPositionHelper.BuildDecodePositionIds(current, kvCache, ropeDelta);
                            positionIds = decodePositionIds;
                        }

                        using var logits = firstStep
                            ? _thinker.forward(current, positionIds: positionIds, kvCache: kvCache, visionPixelValues: pixels, visionGridThw: grid)
                            : ((ICausalLM)_thinker).forward(current, positionIds: positionIds, kvCache: kvCache);

                        next = SampleNextToken(logits[0, -1, ..], config);
                    }
                    finally
                    {
                        decodePositionIds?.Dispose();
                    }
                }

                if (IsEos(next))
                {
                    break;
                }

                tokens.Add(next);
                if (step > 0)
                {
                    current.Dispose();
                }

                current = CreateSingleTokenTensor(next);
                firstStep = false;

                if (kvCache.GetSeqLength() > MaxCacheLen)
                {
                    kvCache.Trim(MaxCacheLen);
                }

                if ((step + 1) % 30 == 0)
                {
                    CollectNativeTensorMemory();
                }
            }
        }
        finally
        {
            if (!ReferenceEquals(current, inputIds))
            {
                current.Dispose();
            }

            kvCache.Dispose();
            CollectNativeTensorMemory();
        }

        return _tokenizer.Decode(tokens, skipSpecialTokens: true).Trim();
    }

    private string RunCompletionFromPipeline(
        Qwen25OmniMmInfo mmInfo,
        float? temperature,
        float? topP,
        int? maxTokens)
    {
        if (mmInfo.VisionInputs.Count > 0)
        {
            return RunVisionTextCompletion(mmInfo, temperature, topP, maxTokens);
        }

        if (mmInfo.Audios.Count > 0)
        {
            using var mel = LoadMelSpectrogram(mmInfo.Audios[0].Path);
            return RunOmniTextCompletion(mmInfo.Messages, mel, temperature ?? 0f, topP ?? 1f, maxTokens);
        }

        return RunTextCompletion(mmInfo.Messages, temperature, topP, maxTokens);
    }

    private string RunTextCompletion(IReadOnlyList<OpenAIMessage> messages, float? temperature, float? topP, int? maxTokens)
    {
        var promptIds = BuildTextPromptIds(messages);
        using var inputIds = CreateInputIdsTensor(promptIds);
        var config = BuildGenerationConfig(temperature, topP, maxTokens);
        return DecodeGeneratedTokens(_thinker, inputIds, config);
    }

    private IEnumerable<string> DecodeGeneratedTextDeltas(
        Tensor inputIds,
        Tensor? audioFeatures,
        GenerationConfig config,
        CancellationToken cancellationToken)
    {
        var decodedTokenIds = new List<int>();
        var emittedLength = 0;
        using var noGrad = no_grad();
        var kvCache = new KVCache();
        var current = inputIds;
        var firstStep = true;
        const int MaxCacheLen = 2048;
        try
        {
            using var audio = audioFeatures is null
                ? null
                : (_modelDtype is not null
                    ? audioFeatures.to(_modelDtype.Value, _device)
                    : audioFeatures.to(_device));

            for (var step = 0; step < config.MaxNewTokens; step++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                int next;
                using (var scope = NewDisposeScope())
                {
                    using var logits = audio is not null && firstStep
                        ? _thinker.forward(current, inputFeatures: audio, positionIds: null, kvCache: kvCache)
                        : ((ICausalLM)_thinker).forward(current, kvCache: kvCache);

                    next = SampleNextToken(logits[0, -1, ..], config);
                }

                if (IsEos(next))
                {
                    break;
                }

                decodedTokenIds.Add(next);
                string decoded = _tokenizer.Decode(decodedTokenIds, skipSpecialTokens: true);
                if (decoded.Length > emittedLength)
                {
                    string delta = decoded[emittedLength..];
                    emittedLength = decoded.Length;
                    if (!string.IsNullOrEmpty(delta))
                    {
                        yield return delta;
                    }
                }

                if (step > 0)
                {
                    current.Dispose();
                }

                current = CreateSingleTokenTensor(next);
                firstStep = false;

                if (kvCache.GetSeqLength() > MaxCacheLen)
                {
                    kvCache.Trim(MaxCacheLen);
                }

                if ((step + 1) % 30 == 0)
                {
                    CollectNativeTensorMemory();
                }
            }
        }
        finally
        {
            if (!ReferenceEquals(current, inputIds))
            {
                current.Dispose();
            }

            kvCache.Dispose();
            CollectNativeTensorMemory();
        }
    }

    private string RunOmniTextCompletion(IReadOnlyList<OpenAIMessage> messages, Tensor audioFeatures, float? temperature, float? topP, int? maxTokens)
    {
        var promptIds = BuildOmniPromptIds(messages, audioFeatures);
        using var inputIds = CreateInputIdsTensor(promptIds);
        using var audio = _modelDtype is not null
            ? audioFeatures.to(_modelDtype.Value, _device)
            : audioFeatures.to(_device);
        var config = BuildGenerationConfig(temperature, topP, maxTokens);

        var tokens = new List<int>();
        using var noGrad = no_grad();
        var kvCache = new KVCache();
        var current = inputIds;
        var firstStep = true;
        const int MaxCacheLen = 2048;
        try
        {
            for (var step = 0; step < config.MaxNewTokens; step++)
            {
                int next;
                using (var scope = NewDisposeScope())
                {
                    using var logits = firstStep
                        ? _thinker.forward(current, inputFeatures: audio, positionIds: null, kvCache: kvCache)
                        : ((ICausalLM)_thinker).forward(current, kvCache: kvCache);

                    next = SampleNextToken(logits[0, -1, ..], config);
                }

                if (IsEos(next))
                {
                    break;
                }

                tokens.Add(next);
                if (step > 0)
                {
                    current.Dispose();
                }

                current = CreateSingleTokenTensor(next);
                firstStep = false;

                if (kvCache.GetSeqLength() > MaxCacheLen)
                {
                    kvCache.Trim(MaxCacheLen);
                }

                if ((step + 1) % 30 == 0)
                {
                    CollectNativeTensorMemory();
                }
            }
        }
        finally
        {
            if (!ReferenceEquals(current, inputIds))
            {
                current.Dispose();
            }

            kvCache.Dispose();
            CollectNativeTensorMemory();
        }

        return _tokenizer.Decode(tokens, skipSpecialTokens: true).Trim();
    }

    internal string TranscribeAudio(Tensor audioFeatures)
    {
        var promptIds = BuildAudioTranscriptionPromptIds(audioFeatures);
        using var inputIds = CreateInputIdsTensor(promptIds);
        using var audio = _modelDtype is not null
            ? audioFeatures.to(_modelDtype.Value, _device)
            : audioFeatures.to(_device);
        var config = new GenerationConfig
        {
            MaxNewTokens = 128,
            Temperature = 0f,
            TopP = 1f,
            TopK = 1,
            DoSample = false,
        };

        var tokens = new List<int>();
        using var noGrad = no_grad();
        var kvCache = new KVCache();
        var current = inputIds;
        var firstStep = true;
        const int MaxCacheLen = 2048;
        try
        {
            for (var step = 0; step < config.MaxNewTokens; step++)
            {
                int next;
                using (var scope = NewDisposeScope())
                {
                    using var logits = firstStep
                        ? _thinker.forward(current, inputFeatures: audio, positionIds: null, kvCache: kvCache)
                        : ((ICausalLM)_thinker).forward(current, kvCache: kvCache);

                    next = SampleNextToken(logits[0, -1, ..], config);
                }

                if (IsEos(next))
                {
                    break;
                }

                tokens.Add(next);
                if (step > 0)
                {
                    current.Dispose();
                }

                current = CreateSingleTokenTensor(next);
                firstStep = false;

                if (kvCache.GetSeqLength() > MaxCacheLen)
                {
                    kvCache.Trim(MaxCacheLen);
                }

                if ((step + 1) % 30 == 0)
                {
                    CollectNativeTensorMemory();
                }
            }
        }
        finally
        {
            if (!ReferenceEquals(current, inputIds))
            {
                current.Dispose();
            }

            kvCache.Dispose();
            CollectNativeTensorMemory();
        }

        return _tokenizer.Decode(tokens, skipSpecialTokens: true).Trim();
    }

    private string DecodeGeneratedTokens(Qwen25OmniForConditionalGeneration model, Tensor inputIds, GenerationConfig config)
    {
        var tokens = new List<int>();
        using var noGrad = no_grad();
        foreach (var token in TextGenerator.Generate(model, inputIds, config, _tokenizer.EosTokenId ?? -1, _tokenizer.ImEndId))
        {
            tokens.Add(token);
        }

        return _tokenizer.Decode(tokens, skipSpecialTokens: true).Trim();
    }

    private GenerationConfig BuildGenerationConfig(float? temperature, float? topP, int? maxTokens)
        => new()
        {
            MaxNewTokens = Math.Clamp(maxTokens ?? 256, 1, 1024),
            Temperature = temperature ?? 0.2f,
            TopP = topP ?? 0.9f,
            TopK = 40,
            DoSample = (temperature ?? 0.2f) > 0,
        };

    private (string AudioBase64, string? Warning) GenerateTalkerAudioBase64(
        IReadOnlyList<OpenAIMessage> messages,
        string assistantReply,
        Tensor? audioFeatures,
        string? voice)
    {
        var voiceProfile = ResolveVoiceProfile(voice, out var voiceWarning);

        if (_token2Wav is null)
        {
            if (_audioSynthesizer is not null)
            {
                var configuredAudio = _audioSynthesizer.SynthesizeToWavBase64(assistantReply, voiceProfile.Name);
                var configuredWarning = string.IsNullOrWhiteSpace(voiceWarning)
                    ? ConfiguredAudioFallbackWarning
                    : $"{voiceWarning} {ConfiguredAudioFallbackWarning}";
                return (configuredAudio, configuredWarning);
            }

            var managedAudio = ManagedSpeechSynthesizer.SynthesizeToWavBase64(assistantReply, voiceProfile.Name);
            var warning = string.IsNullOrWhiteSpace(voiceWarning)
                ? ManagedAudioFallbackWarning
                : $"{voiceWarning} {ManagedAudioFallbackWarning}";
            return (managedAudio, warning);
        }

        var synthMessages = messages.ToList();
        synthMessages.Add(new OpenAIMessage { Role = "assistant", Content = assistantReply });

        var inputIds = audioFeatures is null
            ? BuildTextPromptIds(synthMessages)
            : BuildOmniPromptIds(synthMessages, audioFeatures);

        using var noGrad = no_grad();
        using var scope = NewDisposeScope();
        using var ids = CreateInputIdsTensor(inputIds);
        using var audio = audioFeatures is null
            ? null
            : (_modelDtype is not null
                ? audioFeatures.to(_modelDtype.Value, _device)
                : audioFeatures.to(_device));
        using var logits = audio is null
            ? ((ICausalLM)_thinker).forward(ids)
            : _thinker.forward(inputIds: ids, inputFeatures: audio, positionIds: null, kvCache: null);
        using var waveform = _token2Wav.forward(logits);
        using var flatWaveform = waveform.flatten();
        using var floatWaveform = flatWaveform.to_type(ScalarType.Float32);
        using var cpuWaveform = floatWaveform.cpu();

        var flat = cpuWaveform.data<float>().ToArray();
        flat = ApplyVoiceProfile(flat, voiceProfile);
        var wavBytes = WavCodec.WritePcm16Wav(flat, 24_000);
        CollectNativeTensorMemory();
        return (Convert.ToBase64String(wavBytes), voiceWarning);
    }

    private int[] BuildTextPromptIds(IReadOnlyList<OpenAIMessage> messages)
    {
        var chatMessages = messages
            .Select(message => new ChatMessage(NormalizeRole(message.Role), FlattenMessage(message)))
            .Where(message => !string.IsNullOrWhiteSpace(message.Content))
            .ToList();

        return _tokenizer.EncodeChatTemplate(chatMessages);
    }

    private static IReadOnlyList<OpenAIMessage> ApplyResponseInstructions(
        IReadOnlyList<OpenAIMessage> messages,
        string? instructions)
    {
        if (string.IsNullOrWhiteSpace(instructions))
        {
            return messages;
        }

        var list = messages.ToList();
        if (list.Count > 0 && string.Equals(list[0].Role, "system", StringComparison.OrdinalIgnoreCase))
        {
            list[0] = list[0] with
            {
                Content = string.IsNullOrWhiteSpace(list[0].Content)
                    ? instructions
                    : $"{instructions}\n\n{list[0].Content}",
            };
        }
        else
        {
            list.Insert(0, new OpenAIMessage
            {
                Role = "system",
                Content = instructions,
            });
        }

        return list;
    }

    private static IReadOnlyList<OpenAIMessage> BuildToolAwareMessages(
        IReadOnlyList<OpenAIMessage> messages,
        IReadOnlyList<OpenAITool>? tools,
        JsonElement? toolChoice)
    {
        if (tools is null || tools.Count == 0 || ToolChoiceIsNone(toolChoice))
        {
            return messages;
        }

        var requiredToolName = ResolveRequiredToolName(toolChoice);
        var instruction = new StringBuilder();
        instruction.AppendLine("You have access to the following tools.");
        instruction.AppendLine("When a tool is needed, respond only with JSON in this exact shape:");
        instruction.AppendLine("""{"tool_calls":[{"name":"tool_name","arguments":{}}]}""");
        instruction.AppendLine("When no tool is needed, answer normally without JSON.");
        if (!string.IsNullOrWhiteSpace(requiredToolName))
        {
            instruction.AppendLine($"You must call the tool named '{requiredToolName}'.");
        }
        else if (ToolChoiceIsRequired(toolChoice))
        {
            instruction.AppendLine("You must call one of the provided tools.");
        }

        instruction.AppendLine("Tools:");
        instruction.AppendLine(JsonSerializer.Serialize(tools, new JsonSerializerOptions
        {
            WriteIndented = false,
            Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        }));

        var list = messages.ToList();
        list.Insert(0, new OpenAIMessage
        {
            Role = "system",
            Content = instruction.ToString(),
        });
        return list;
    }

    private static IReadOnlyList<OpenAIToolCall> TryParseToolCalls(string text, IReadOnlyList<OpenAITool>? tools)
    {
        if (tools is null || tools.Count == 0 || string.IsNullOrWhiteSpace(text))
        {
            return Array.Empty<OpenAIToolCall>();
        }

        var payload = ExtractJsonPayload(text);
        if (string.IsNullOrWhiteSpace(payload))
        {
            return Array.Empty<OpenAIToolCall>();
        }

        try
        {
            using var document = JsonDocument.Parse(payload);
            var root = document.RootElement;
            var toolNames = tools
                .Where(tool => string.Equals(tool.Type, "function", StringComparison.OrdinalIgnoreCase))
                .Select(tool => tool.Function?.Name)
                .Where(name => !string.IsNullOrWhiteSpace(name))
                .Select(name => name!)
                .ToHashSet(StringComparer.Ordinal);
            var parsed = new List<OpenAIToolCall>();

            if (root.TryGetProperty("tool_calls", out var toolCalls) && toolCalls.ValueKind == JsonValueKind.Array)
            {
                foreach (var item in toolCalls.EnumerateArray())
                {
                    var toolCall = ParseToolCall(item, toolNames);
                    if (toolCall is not null)
                    {
                        parsed.Add(toolCall);
                    }
                }
            }
            else
            {
                var toolCall = ParseToolCall(root, toolNames);
                if (toolCall is not null)
                {
                    parsed.Add(toolCall);
                }
            }

            return parsed;
        }
        catch (JsonException)
        {
            return Array.Empty<OpenAIToolCall>();
        }
    }

    private static OpenAIToolCall? ParseToolCall(JsonElement element, HashSet<string> allowedToolNames)
    {
        JsonElement source = element;
        if (element.TryGetProperty("function", out var functionElement) && functionElement.ValueKind == JsonValueKind.Object)
        {
            source = functionElement;
        }

        var name = ReadString(source, "name");
        if (string.IsNullOrWhiteSpace(name))
        {
            return null;
        }

        if (allowedToolNames.Count > 0 && !allowedToolNames.Contains(name))
        {
            return null;
        }

        var arguments = "{}";
        if (source.TryGetProperty("arguments", out var argumentsElement))
        {
            arguments = argumentsElement.ValueKind == JsonValueKind.String
                ? argumentsElement.GetString() ?? "{}"
                : argumentsElement.GetRawText();
        }

        return new OpenAIToolCall
        {
            Id = ReadString(element, "id") ?? $"call_{Guid.NewGuid():N}",
            Function = new OpenAIFunctionCall
            {
                Name = name,
                Arguments = string.IsNullOrWhiteSpace(arguments) ? "{}" : arguments,
            },
        };
    }

    private static string? ExtractJsonPayload(string text)
    {
        var trimmed = text.Trim();
        if (trimmed.StartsWith("```", StringComparison.Ordinal))
        {
            var firstNewline = trimmed.IndexOf('\n');
            var lastFence = trimmed.LastIndexOf("```", StringComparison.Ordinal);
            if (firstNewline >= 0 && lastFence > firstNewline)
            {
                trimmed = trimmed[(firstNewline + 1)..lastFence].Trim();
            }
        }

        if (trimmed.StartsWith('{') && trimmed.EndsWith('}'))
        {
            return trimmed;
        }

        var start = trimmed.IndexOf('{');
        var end = trimmed.LastIndexOf('}');
        return start >= 0 && end > start
            ? trimmed[start..(end + 1)]
            : null;
    }

    private static bool ToolChoiceIsNone(JsonElement? toolChoice)
        => toolChoice is not null
           && toolChoice.Value.ValueKind == JsonValueKind.String
           && string.Equals(toolChoice.Value.GetString(), "none", StringComparison.OrdinalIgnoreCase);

    private static bool ToolChoiceIsRequired(JsonElement? toolChoice)
        => toolChoice is not null
           && toolChoice.Value.ValueKind == JsonValueKind.String
           && string.Equals(toolChoice.Value.GetString(), "required", StringComparison.OrdinalIgnoreCase);

    private static string? ResolveRequiredToolName(JsonElement? toolChoice)
    {
        if (toolChoice is null || toolChoice.Value.ValueKind != JsonValueKind.Object)
        {
            return null;
        }

        var root = toolChoice.Value;
        if (root.TryGetProperty("function", out var function) &&
            function.ValueKind == JsonValueKind.Object)
        {
            return ReadString(function, "name");
        }

        return ReadString(root, "name");
    }

    private static string? ReadString(JsonElement element, string propertyName)
        => element.TryGetProperty(propertyName, out var property) && property.ValueKind == JsonValueKind.String
            ? property.GetString()
            : null;

    private int[] BuildOmniPromptIds(IReadOnlyList<OpenAIMessage> messages, Tensor audioFeatures)
    {
        var audioTokenCount = Qwen25OmniAudioProcessor.EstimateAudioTokenCount(audioFeatures);
        var ids = new List<int>();
        ids.Add(_tokenizer.ImStartId);
        ids.AddRange(_tokenizer.Encode("system\n", addSpecialTokens: false));
        ids.AddRange(_tokenizer.Encode(GetSystemPrompt(messages), addSpecialTokens: false));
        ids.Add(_tokenizer.ImEndId);

        var audioInserted = false;
        foreach (var message in messages)
        {
            var role = NormalizeRole(message.Role);
            if (string.Equals(role, "system", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var content = FlattenMessage(message);
            if (string.IsNullOrWhiteSpace(content) && !MessageContainsAudio(message))
            {
                continue;
            }

            ids.Add(_tokenizer.ImStartId);
            ids.AddRange(_tokenizer.Encode($"{role}\n", addSpecialTokens: false));

            if (!audioInserted && string.Equals(role, "user", StringComparison.OrdinalIgnoreCase) && MessageContainsAudio(message))
            {
                ids.Add(_config.ThinkerConfig.AudioStartTokenId);
                ids.AddRange(Enumerable.Repeat(_config.ThinkerConfig.AudioTokenIndex, audioTokenCount));
                ids.Add(_config.ThinkerConfig.AudioEndTokenId);
                audioInserted = true;
            }

            if (!string.IsNullOrWhiteSpace(content))
            {
                ids.AddRange(_tokenizer.Encode(content, addSpecialTokens: false));
            }

            ids.Add(_tokenizer.ImEndId);
        }

        if (!audioInserted)
        {
            ids.Add(_tokenizer.ImStartId);
            ids.AddRange(_tokenizer.Encode("user\n", addSpecialTokens: false));
            ids.Add(_config.ThinkerConfig.AudioStartTokenId);
            ids.AddRange(Enumerable.Repeat(_config.ThinkerConfig.AudioTokenIndex, audioTokenCount));
            ids.Add(_config.ThinkerConfig.AudioEndTokenId);
            ids.Add(_tokenizer.ImEndId);
        }

        ids.Add(_tokenizer.ImStartId);
        ids.AddRange(_tokenizer.Encode("assistant\n", addSpecialTokens: false));
        return ids.ToArray();
    }

    private int[] BuildAudioTranscriptionPromptIds(Tensor audioFeatures)
    {
        var audioTokenCount = Qwen25OmniAudioProcessor.EstimateAudioTokenCount(audioFeatures);
        var ids = new List<int>();
        ids.Add(_tokenizer.ImStartId);
        ids.AddRange(_tokenizer.Encode("system\n", addSpecialTokens: false));
        ids.AddRange(_tokenizer.Encode("You are a speech recognition model.", addSpecialTokens: false));
        ids.Add(_tokenizer.ImEndId);
        ids.Add(_tokenizer.ImStartId);
        ids.AddRange(_tokenizer.Encode("user\n", addSpecialTokens: false));
        ids.AddRange(_tokenizer.Encode("Transcribe the audio into plain text without punctuation.", addSpecialTokens: false));
        ids.Add(_config.ThinkerConfig.AudioStartTokenId);
        ids.AddRange(Enumerable.Repeat(_config.ThinkerConfig.AudioTokenIndex, audioTokenCount));
        ids.Add(_config.ThinkerConfig.AudioEndTokenId);
        ids.Add(_tokenizer.ImEndId);
        ids.Add(_tokenizer.ImStartId);
        ids.AddRange(_tokenizer.Encode("assistant\n", addSpecialTokens: false));
        return ids.ToArray();
    }

    private static IReadOnlyList<OpenAIMessage> ReplaceAudioMessagesWithTranscript(
        IReadOnlyList<OpenAIMessage> messages,
        string transcript)
    {
        if (string.IsNullOrWhiteSpace(transcript))
        {
            return messages;
        }

        var rewritten = new List<OpenAIMessage>(messages.Count);
        foreach (var message in messages)
        {
            if (message.Parts is null || message.Parts.Count == 0)
            {
                rewritten.Add(message);
                continue;
            }

            var parts = new List<OpenAIContentPart>();
            var text = new StringBuilder();
            foreach (var part in message.Parts)
            {
                if (string.Equals(part.Type, "input_audio", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                if (string.Equals(part.Type, "text", StringComparison.OrdinalIgnoreCase) && !string.IsNullOrWhiteSpace(part.Text))
                {
                    text.Append(part.Text);
                }
                else
                {
                    parts.Add(part);
                }
            }

            if (message.Parts.Any(part => string.Equals(part.Type, "input_audio", StringComparison.OrdinalIgnoreCase)))
            {
                if (text.Length > 0)
                {
                    text.Append(' ');
                }

                text.Append(transcript);
                rewritten.Add(new OpenAIMessage
                {
                    Role = message.Role,
                    Content = text.ToString(),
                    Parts = parts.Count > 0 ? parts : null,
                });
            }
            else
            {
                rewritten.Add(message);
            }
        }

        return rewritten;
    }

    private static bool MessageContainsAudio(OpenAIMessage message)
        => message.Parts?.Any(part => string.Equals(part.Type, "input_audio", StringComparison.OrdinalIgnoreCase)) == true;

    private static bool IsDegenerateModelText(string text)
    {
        var trimmed = text.Trim();
        if (string.IsNullOrEmpty(trimmed))
        {
            return true;
        }

        if (trimmed.Length <= 16 && trimmed.StartsWith('<') && trimmed.EndsWith('>'))
        {
            return true;
        }

        return trimmed.All(ch => !char.IsLetterOrDigit(ch) && !IsCjk(ch));
    }

    private static bool IsCjk(char ch) => ch >= '\u3400' && ch <= '\u9fff';

    private int[] BuildVisionPromptIds(Qwen25OmniMmInfo mmInfo)
    {
        var messages = mmInfo.Messages;
        var imageIndex = 0;
        var videoIndex = 0;
        var ids = new List<int>();
        ids.Add(_tokenizer.ImStartId);
        ids.AddRange(_tokenizer.Encode("system\n", addSpecialTokens: false));
        ids.AddRange(_tokenizer.Encode(GetSystemPrompt(messages), addSpecialTokens: false));
        ids.Add(_tokenizer.ImEndId);

        foreach (var message in messages.Where(message => !string.Equals(message.Role, "system", StringComparison.OrdinalIgnoreCase)))
        {
            ids.Add(_tokenizer.ImStartId);
            ids.AddRange(_tokenizer.Encode($"{NormalizeRole(message.Role)}\n", addSpecialTokens: false));
            if (message.Parts is null || message.Parts.Count == 0)
            {
                ids.AddRange(_tokenizer.Encode(FlattenMessage(message), addSpecialTokens: false));
            }
            else
            {
                foreach (var part in message.Parts)
                {
                    if (string.Equals(part.Type, "text", StringComparison.OrdinalIgnoreCase) && !string.IsNullOrWhiteSpace(part.Text))
                    {
                        ids.AddRange(_tokenizer.Encode(part.Text, addSpecialTokens: false));
                    }
                    else if (string.Equals(part.Type, "image_url", StringComparison.OrdinalIgnoreCase) && imageIndex < mmInfo.Images.Count)
                    {
                        var image = mmInfo.Images[imageIndex++];
                        if (image.VisionInput is not null)
                        {
                            AppendVisionTokens(ids, image.VisionInput);
                        }
                    }
                    else if (string.Equals(part.Type, "video", StringComparison.OrdinalIgnoreCase) && videoIndex < mmInfo.Videos.Count)
                    {
                        var video = mmInfo.Videos[videoIndex++];
                        if (video.FrameInputs is not null)
                        {
                            ids.Add(_config.ThinkerConfig.VisionStartTokenId);
                            foreach (var frame in video.FrameInputs)
                            {
                                ids.AddRange(Enumerable.Repeat(frame.TokenIndex, frame.TokenCount));
                            }
                            ids.Add(_config.ThinkerConfig.VisionEndTokenId);
                        }
                    }
                }
            }
            ids.Add(_tokenizer.ImEndId);
        }
        ids.Add(_tokenizer.ImStartId);
        ids.AddRange(_tokenizer.Encode("assistant\n", addSpecialTokens: false));
        return ids.ToArray();
    }

    private void AppendVisionTokens(List<int> ids, Qwen25OmniVisionTensor visionInput)
    {
        ids.Add(_config.ThinkerConfig.VisionStartTokenId);
        ids.AddRange(Enumerable.Repeat(visionInput.TokenIndex, visionInput.TokenCount));
        ids.Add(_config.ThinkerConfig.VisionEndTokenId);
    }

    private Tensor CatVisionPixelValues(IReadOnlyList<Qwen25OmniVisionTensor> visionInputs)
    {
        if (visionInputs.Count == 1)
        {
            return visionInputs[0].PixelValues.to(_device);
        }

        var tensors = visionInputs.Select(input => input.PixelValues.to(_device)).ToArray();
        try
        {
            return torch.cat(tensors, dim: 0);
        }
        finally
        {
            foreach (var tensor in tensors)
            {
                tensor.Dispose();
            }
        }
    }

    private Tensor BuildVisionTokenTypeIds(Tensor inputIds)
    {
        using var scope = NewDisposeScope();
        var tokenTypeIds = zeros_like(inputIds, dtype: ScalarType.Int64);
        tokenTypeIds = where(inputIds == _config.ThinkerConfig.ImageTokenIndex, ones_like(tokenTypeIds), tokenTypeIds);
        tokenTypeIds = where(inputIds == _config.ThinkerConfig.VideoTokenIndex, ones_like(tokenTypeIds) * 2, tokenTypeIds);
        return scope.MoveToOuter(tokenTypeIds);
    }

    private Tensor CatVisionGridThw(IReadOnlyList<Qwen25OmniVisionTensor> visionInputs)
    {
        if (visionInputs.Count == 1)
        {
            return visionInputs[0].ImageGridThw.to(_device);
        }

        var tensors = visionInputs.Select(input => input.ImageGridThw.to(_device)).ToArray();
        try
        {
            return torch.cat(tensors, dim: 0);
        }
        finally
        {
            foreach (var tensor in tensors)
            {
                tensor.Dispose();
            }
        }
    }

    private Tensor CatVisionTemporalStrides(IReadOnlyList<Qwen25OmniVisionTensor> visionInputs)
    {
        var values = visionInputs
            .Select(input => (long)Math.Max(1, input.TemporalPositionStride))
            .ToArray();
        return tensor(values, dtype: ScalarType.Int64, device: _device);
    }

    private Tensor CreateInputIdsTensor(IEnumerable<int> tokenIds)
    {
        using var scope = NewDisposeScope();
        var values = tokenIds.Select(static tokenId => (long)tokenId).ToArray();
        var baseTensor = tensor(values, dtype: ScalarType.Int64, device: _device);
        return scope.MoveToOuter(baseTensor.unsqueeze(0));
    }

    private Tensor CreateSingleTokenTensor(long tokenId)
    {
        using var scope = NewDisposeScope();
        var baseTensor = tensor(new long[] { tokenId }, dtype: ScalarType.Int64, device: _device);
        return scope.MoveToOuter(baseTensor.unsqueeze(0));
    }

    private static string FlattenMessage(OpenAIMessage message)
    {
        if (!string.IsNullOrWhiteSpace(message.Content))
        {
            return message.Content!;
        }

        if (message.Parts is null)
        {
            return string.Empty;
        }

        var text = new StringBuilder();
        foreach (var part in message.Parts)
        {
            if (string.Equals(part.Type, "text", StringComparison.OrdinalIgnoreCase) && !string.IsNullOrWhiteSpace(part.Text))
            {
                text.Append(part.Text);
            }
        }

        return text.ToString();
    }

    private static string GetSystemPrompt(IReadOnlyList<OpenAIMessage> messages)
    {
        var systemMessage = messages.FirstOrDefault(message => string.Equals(message.Role, "system", StringComparison.OrdinalIgnoreCase));
        var content = FlattenMessage(systemMessage ?? new OpenAIMessage { Content = AudioOutputSystemPrompt });
        return string.IsNullOrWhiteSpace(content) ? AudioOutputSystemPrompt : content;
    }

    private static string NormalizeRole(string role)
    {
        if (string.IsNullOrWhiteSpace(role))
        {
            return "user";
        }

        return role.Trim().ToLowerInvariant();
    }

    private int SampleNextToken(Tensor logits, GenerationConfig config)
    {
        return (int)TorchHelper.SampleTokenId(logits, config);
    }

    private bool IsEos(int tokenId)
    {
        var eos = _tokenizer.EosTokenId ?? -1;
        return tokenId == eos || tokenId == _tokenizer.ImEndId;
    }

    internal static void CollectNativeTensorMemory()
    {
        if (string.Equals(Environment.GetEnvironmentVariable("QWENSHARP_DEBUG_CUDA_GC"), "1", StringComparison.Ordinal))
        {
            Console.WriteLine($"[QwenSharp][CUDA-GC] Triggering managed/native tensor collection at {DateTime.UtcNow:O}");
        }

        GC.Collect();
        GC.WaitForPendingFinalizers();
        GC.Collect();
    }

    private Tensor LoadMelSpectrogram(string path) => Qwen25OmniAudioProcessor.LoadMelSpectrogram(path);

    private static VoiceProfile ResolveVoiceProfile(string? voice, out string? warning)
    {
        if (!string.IsNullOrWhiteSpace(voice) && VoiceProfiles.TryGetValue(voice.Trim(), out var profile))
        {
            warning = null;
            return profile;
        }

        warning = string.IsNullOrWhiteSpace(voice)
            ? null
            : $"Unsupported voice '{voice}'. Falling back to {DefaultVoiceProfile.Name}.";
        return DefaultVoiceProfile;
    }

    private static (byte[] AudioBytes, string ContentType) ConvertSpeechOutput(byte[] wavBytes, string responseFormat)
    {
        return responseFormat switch
        {
            "wav" => (wavBytes, "audio/wav"),
            "pcm" => (ExtractPcm16FromWav(wavBytes), "application/octet-stream"),
            _ => throw new InvalidOperationException($"Unsupported response_format '{responseFormat}'. Supported values: wav, pcm."),
        };
    }

    private static byte[] ExtractPcm16FromWav(byte[] wavBytes)
    {
        if (wavBytes.Length < 44)
        {
            throw new InvalidOperationException("Invalid WAV payload.");
        }

        using var stream = new MemoryStream(wavBytes, writable: false);
        using var reader = new BinaryReader(stream, Encoding.ASCII, leaveOpen: false);
        stream.Seek(12, SeekOrigin.Begin);

        while (stream.Position + 8 <= stream.Length)
        {
            var chunkId = Encoding.ASCII.GetString(reader.ReadBytes(4));
            var chunkSize = reader.ReadInt32();
            if (chunkSize < 0 || stream.Position + chunkSize > stream.Length)
            {
                throw new InvalidOperationException("Invalid WAV chunk size.");
            }

            if (string.Equals(chunkId, "data", StringComparison.Ordinal))
            {
                return reader.ReadBytes(chunkSize);
            }

            stream.Seek(chunkSize, SeekOrigin.Current);
            if ((chunkSize & 1) != 0 && stream.Position < stream.Length)
            {
                stream.Seek(1, SeekOrigin.Current);
            }
        }

        throw new InvalidOperationException("WAV payload does not contain a data chunk.");
    }

    private static float[] ApplyVoiceProfile(float[] samples, VoiceProfile profile)
    {
        if (samples.Length == 0)
        {
            return samples;
        }

        var voiced = samples;
        if (MathF.Abs(profile.PitchScale - 1f) > 0.0001f)
        {
            var pitchedLength = Math.Max(1, (int)Math.Round(samples.Length / profile.PitchScale));
            voiced = ResampleLinear(samples, pitchedLength);
            voiced = ResampleLinear(voiced, samples.Length);
        }

        if (MathF.Abs(profile.Gain - 1f) > 0.0001f)
        {
            for (var i = 0; i < voiced.Length; i++)
            {
                var sample = voiced[i] * profile.Gain;
                voiced[i] = Math.Clamp(sample, -1f, 1f);
            }
        }

        return voiced;
    }

    private static float[] ResampleLinear(float[] samples, int targetLength)
    {
        if (samples.Length == 0 || targetLength <= 0 || samples.Length == targetLength)
        {
            return samples;
        }

        if (samples.Length == 1)
        {
            return Enumerable.Repeat(samples[0], targetLength).ToArray();
        }

        var output = new float[targetLength];
        var ratio = (samples.Length - 1) / (double)(targetLength - 1);
        for (var i = 0; i < targetLength; i++)
        {
            var sourceIndex = i * ratio;
            var index0 = (int)Math.Floor(sourceIndex);
            var index1 = Math.Min(index0 + 1, samples.Length - 1);
            var t = (float)(sourceIndex - index0);
            output[i] = samples[index0] * (1f - t) + samples[index1] * t;
        }

        return output;
    }

    internal sealed class Qwen25OmniRealtimeGenerationContext : IDisposable
    {
        public Qwen25OmniRealtimeGenerationContext(
            Qwen25OmniMmInfo mmInfo,
            IReadOnlyList<OpenAIMessage> messages,
            Tensor? audioFeatures,
            bool hasVisionInputs,
            IReadOnlyList<string> warnings)
        {
            MmInfo = mmInfo;
            Messages = messages;
            AudioFeatures = audioFeatures;
            HasVisionInputs = hasVisionInputs;
            Warnings = warnings;
        }

        public Qwen25OmniMmInfo MmInfo { get; }

        public IReadOnlyList<OpenAIMessage> Messages { get; }

        public Tensor? AudioFeatures { get; }

        public bool HasVisionInputs { get; }

        public IReadOnlyList<string> Warnings { get; }

        public void Dispose()
        {
            AudioFeatures?.Dispose();
        }
    }

    private sealed record VoiceProfile(string Name, float PitchScale, float Gain);

    public void Dispose()
    {
        ((IDisposable)_thinker).Dispose();
        (_token2Wav as IDisposable)?.Dispose();
        _audioSynthesizer?.Dispose();
    }
}
